// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProjectManagement.Models;

#nullable disable

namespace ProjectManagement.Migrations
{
    [DbContext(typeof(ProjectManagementContext))]
    [Migration("20260407230457_firstMigration")]
    partial class firstMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ProjectManagement.Models.TbAttachment", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime");

                    b.Property<string>("FileUrl")
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<int?>("TaskId")
                        .HasColumnType("int");

                    b.Property<int?>("UploadedBy")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__Attachme__3214EC073AE3B018");

                    b.HasIndex("TaskId");

                    b.HasIndex("UploadedBy");

                    b.ToTable("TbAttachments");
                });

            modelBuilder.Entity("ProjectManagement.Models.TbComment", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime");

                    b.Property<int?>("TaskId")
                        .HasColumnType("int");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__Comments__3214EC07279B244E");

                    b.HasIndex("TaskId");

                    b.HasIndex("UserId");

                    b.ToTable("TbComments");
                });

            modelBuilder.Entity("ProjectManagement.Models.TbNotification", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime");

                    b.Property<bool?>("IsRead")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("Type")
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__Notifica__3214EC07D6006DDB");

                    b.HasIndex("UserId");

                    b.ToTable("TbNotifications");
                });

            modelBuilder.Entity("ProjectManagement.Models.TbProject", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("Name")
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.HasKey("Id")
                        .HasName("PK__Projects__3214EC077FDC379D");

                    b.HasIndex("CreatedBy");

                    b.ToTable("TbProjects");
                });

            modelBuilder.Entity("ProjectManagement.Models.TbProjectMember", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<DateTime?>("JoinedAt")
                        .HasColumnType("datetime");

                    b.Property<int?>("ProjectId")
                        .HasColumnType("int");

                    b.Property<string>("Role")
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__ProjectM__3214EC07F20E807A");

                    b.HasIndex("ProjectId");

                    b.HasIndex("UserId");

                    b.ToTable("TbProjectMembers");
                });

            modelBuilder.Entity("ProjectManagement.Models.TbTask", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<int?>("AssignedTo")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("datetime");

                    b.Property<string>("Priority")
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<int?>("ProjectId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("Title")
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime");

                    b.HasKey("Id")
                        .HasName("PK__Tasks__3214EC07B727A843");

                    b.HasIndex("AssignedTo");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("ProjectId");

                    b.ToTable("TbTasks");
                });

            modelBuilder.Entity("ProjectManagement.Models.TbTaskHistory", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ChangedAt")
                        .HasColumnType("datetime");

                    b.Property<int?>("ChangedBy")
                        .HasColumnType("int");

                    b.Property<string>("FieldChanged")
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("NewValue")
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("OldValue")
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<int?>("TaskId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__TaskHist__3214EC075D06874D");

                    b.HasIndex("ChangedBy");

                    b.HasIndex("TaskId");

                    b.ToTable("TbTaskHistory", (string)null);
                });

            modelBuilder.Entity("ProjectManagement.Models.TbUser", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime");

                    b.Property<string>("Email")
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("Name")
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("Role")
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("Status")
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.HasKey("Id")
                        .HasName("PK__Users__3214EC07E9B48031");

                    b.ToTable("TbUsers");
                });

            modelBuilder.Entity("ProjectManagement.Models.TbAttachment", b =>
                {
                    b.HasOne("ProjectManagement.Models.TbTask", "Task")
                        .WithMany("TbAttachments")
                        .HasForeignKey("TaskId")
                        .HasConstraintName("FK__Attachmen__TaskI__4CA06362");

                    b.HasOne("ProjectManagement.Models.TbUser", "UploadedByNavigation")
                        .WithMany("TbAttachments")
                        .HasForeignKey("UploadedBy")
                        .HasConstraintName("FK__Attachmen__Uploa__4D94879B");

                    b.Navigation("Task");

                    b.Navigation("UploadedByNavigation");
                });

            modelBuilder.Entity("ProjectManagement.Models.TbComment", b =>
                {
                    b.HasOne("ProjectManagement.Models.TbTask", "Task")
                        .WithMany("TbComments")
                        .HasForeignKey("TaskId")
                        .HasConstraintName("FK__Comments__TaskId__4AB81AF0");

                    b.HasOne("ProjectManagement.Models.TbUser", "User")
                        .WithMany("TbComments")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK__Comments__UserId__4BAC3F29");

                    b.Navigation("Task");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ProjectManagement.Models.TbNotification", b =>
                {
                    b.HasOne("ProjectManagement.Models.TbUser", "User")
                        .WithMany("TbNotifications")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK__Notificat__UserI__4E88ABD4");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ProjectManagement.Models.TbProject", b =>
                {
                    b.HasOne("ProjectManagement.Models.TbUser", "CreatedByNavigation")
                        .WithMany("TbProjects")
                        .HasForeignKey("CreatedBy")
                        .HasConstraintName("FK__Projects__Create__44FF419A");

                    b.Navigation("CreatedByNavigation");
                });

            modelBuilder.Entity("ProjectManagement.Models.TbProjectMember", b =>
                {
                    b.HasOne("ProjectManagement.Models.TbProject", "Project")
                        .WithMany("TbProjectMembers")
                        .HasForeignKey("ProjectId")
                        .HasConstraintName("FK__ProjectMe__Proje__45F365D3");

                    b.HasOne("ProjectManagement.Models.TbUser", "User")
                        .WithMany("TbProjectMembers")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK__ProjectMe__UserI__46E78A0C");

                    b.Navigation("Project");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ProjectManagement.Models.TbTask", b =>
                {
                    b.HasOne("ProjectManagement.Models.TbUser", "AssignedToNavigation")
                        .WithMany("TbTaskAssignedToNavigations")
                        .HasForeignKey("AssignedTo")
                        .HasConstraintName("FK__Tasks__AssignedT__48CFD27E");

                    b.HasOne("ProjectManagement.Models.TbUser", "CreatedByNavigation")
                        .WithMany("TbTaskCreatedByNavigations")
                        .HasForeignKey("CreatedBy")
                        .HasConstraintName("FK__Tasks__CreatedBy__49C3F6B7");

                    b.HasOne("ProjectManagement.Models.TbProject", "Project")
                        .WithMany("TbTasks")
                        .HasForeignKey("ProjectId")
                        .HasConstraintName("FK__Tasks__ProjectId__47DBAE45");

                    b.Navigation("AssignedToNavigation");

                    b.Navigation("CreatedByNavigation");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("ProjectManagement.Models.TbTaskHistory", b =>
                {
                    b.HasOne("ProjectManagement.Models.TbUser", "ChangedByNavigation")
                        .WithMany("TbTaskHistories")
                        .HasForeignKey("ChangedBy")
                        .HasConstraintName("FK__TaskHisto__Chang__5070F446");

                    b.HasOne("ProjectManagement.Models.TbTask", "Task")
                        .WithMany("TbTaskHistories")
                        .HasForeignKey("TaskId")
                        .HasConstraintName("FK__TaskHisto__TaskI__4F7CD00D");

                    b.Navigation("ChangedByNavigation");

                    b.Navigation("Task");
                });

            modelBuilder.Entity("ProjectManagement.Models.TbProject", b =>
                {
                    b.Navigation("TbProjectMembers");

                    b.Navigation("TbTasks");
                });

            modelBuilder.Entity("ProjectManagement.Models.TbTask", b =>
                {
                    b.Navigation("TbAttachments");

                    b.Navigation("TbComments");

                    b.Navigation("TbTaskHistories");
                });

            modelBuilder.Entity("ProjectManagement.Models.TbUser", b =>
                {
                    b.Navigation("TbAttachments");

                    b.Navigation("TbComments");

                    b.Navigation("TbNotifications");

                    b.Navigation("TbProjectMembers");

                    b.Navigation("TbProjects");

                    b.Navigation("TbTaskAssignedToNavigations");

                    b.Navigation("TbTaskCreatedByNavigations");

                    b.Navigation("TbTaskHistories");
                });
#pragma warning restore 612, 618
        }
    }
}
